"""Initial scenario scaffolding for the agentic strategy game app."""

from __future__ import annotations

from agentic_strategy_game_app.contracts import (
    AgentProfile,
    CompanyState,
    MarketForces,
    SimulationConfig,
    WorldState,
)


def list_scenarios() -> list[str]:
    """Return the scenarios available in the current slice."""
    return ["b2b_saas_ai_disruption"]


def build_b2b_saas_ai_disruption_scenario() -> tuple[SimulationConfig, WorldState]:
    """Build the initial strategy-game scenario described in the planning doc."""
    config = SimulationConfig(
        scenario_name="b2b_saas_ai_disruption",
        random_seed=17,
        turn_interval_label="quarter",
        max_turns=12,
        uncertainty_enabled=True,
        allow_random_events=True,
        max_actions_per_turn=2,
        visibility_mode="partial_information",
        metadata={
            "recommended_next_slice": "deterministic_single_turn_engine",
            "scenario_focus": "AI-native disruption in B2B SaaS",
        },
    )
    world = WorldState(
        current_turn=0,
        current_period_label="Q1",
        scenario_name=config.scenario_name,
        market_forces=MarketForces(
            market_size=9_500_000_000.0,
            growth_rate=0.12,
            customer_budget_index=0.58,
            rivalry_intensity=0.61,
            buyer_power=0.56,
            supplier_power=0.28,
            threat_of_new_entry=0.47,
            threat_of_substitution=0.52,
            regulatory_pressure=0.24,
            capital_availability=0.55,
            talent_availability=0.44,
            technology_shift_intensity=0.88,
            macroeconomic_pressure=0.33,
        ),
        companies={
            "incumbent_platform": CompanyState(
                company_id="incumbent_platform",
                name="Incumbent Platform",
                cash=1_600_000_000.0,
                revenue=2_400_000_000.0,
                margin=0.24,
                profit=576_000_000.0,
                market_share=0.42,
                customer_count=1820,
                product_quality=0.72,
                ai_capability=0.51,
                brand_trust=0.81,
                sales_capacity=0.84,
                operational_efficiency=0.76,
                talent_density=0.68,
                technical_debt=0.63,
                regulatory_risk=0.18,
                strategic_momentum=0.52,
                metadata={"archetype": "incumbent"},
            ),
            "ai_native_startup": CompanyState(
                company_id="ai_native_startup",
                name="AI-Native Startup",
                cash=210_000_000.0,
                revenue=84_000_000.0,
                margin=-0.18,
                profit=-15_120_000.0,
                market_share=0.06,
                customer_count=145,
                product_quality=0.79,
                ai_capability=0.92,
                brand_trust=0.49,
                sales_capacity=0.31,
                operational_efficiency=0.43,
                talent_density=0.74,
                technical_debt=0.18,
                regulatory_risk=0.09,
                strategic_momentum=0.74,
                metadata={"archetype": "challenger"},
            ),
            "enterprise_suite_competitor": CompanyState(
                company_id="enterprise_suite_competitor",
                name="Enterprise Suite Competitor",
                cash=2_200_000_000.0,
                revenue=3_100_000_000.0,
                margin=0.19,
                profit=589_000_000.0,
                market_share=0.27,
                customer_count=2410,
                product_quality=0.68,
                ai_capability=0.58,
                brand_trust=0.76,
                sales_capacity=0.88,
                operational_efficiency=0.79,
                talent_density=0.63,
                technical_debt=0.49,
                regulatory_risk=0.22,
                strategic_momentum=0.57,
                metadata={"archetype": "bundler"},
            ),
        },
        ecosystem_agents={
            "incumbent_platform": AgentProfile(
                agent_id="incumbent_platform",
                name="Incumbent Platform Strategy Team",
                agent_type="company",
                objective_function="defend_share_and_transition_to_ai_without_breaking_margins",
                risk_tolerance=0.42,
                cooperation_tendency=0.31,
                aggression_level=0.38,
                price_sensitivity=0.47,
                innovation_bias=0.66,
                capital_discipline=0.73,
                regulatory_sensitivity=0.54,
                time_horizon=8,
                memory_depth=12,
            ),
            "ai_native_startup": AgentProfile(
                agent_id="ai_native_startup",
                name="AI-Native Startup Leadership",
                agent_type="company",
                objective_function="capture_share_before_capital_runs_out",
                risk_tolerance=0.81,
                cooperation_tendency=0.18,
                aggression_level=0.77,
                price_sensitivity=0.59,
                innovation_bias=0.93,
                capital_discipline=0.36,
                regulatory_sensitivity=0.22,
                time_horizon=4,
                memory_depth=8,
            ),
            "enterprise_suite_competitor": AgentProfile(
                agent_id="enterprise_suite_competitor",
                name="Enterprise Suite Competitor Strategy Team",
                agent_type="company",
                objective_function="expand_bundle_share_and_cross_sell_advantage",
                risk_tolerance=0.49,
                cooperation_tendency=0.41,
                aggression_level=0.52,
                price_sensitivity=0.45,
                innovation_bias=0.57,
                capital_discipline=0.71,
                regulatory_sensitivity=0.62,
                time_horizon=6,
                memory_depth=10,
            ),
            "customer_segment_enterprise": AgentProfile(
                agent_id="customer_segment_enterprise",
                name="Enterprise Customer Segment",
                agent_type="customer_segment",
                objective_function="maximize_roi_with_low_switching_risk",
                risk_tolerance=0.28,
                cooperation_tendency=0.47,
                aggression_level=0.12,
                price_sensitivity=0.63,
                innovation_bias=0.41,
                capital_discipline=0.74,
                regulatory_sensitivity=0.34,
                time_horizon=5,
                memory_depth=6,
            ),
            "capital_market": AgentProfile(
                agent_id="capital_market",
                name="Growth Capital Market",
                agent_type="capital_market",
                objective_function="reward_growth_with_credible_unit_economics",
                risk_tolerance=0.37,
                cooperation_tendency=0.24,
                aggression_level=0.18,
                price_sensitivity=0.29,
                innovation_bias=0.46,
                capital_discipline=0.91,
                regulatory_sensitivity=0.41,
                time_horizon=3,
                memory_depth=8,
            ),
            "regulator": AgentProfile(
                agent_id="regulator",
                name="Competition Regulator",
                agent_type="regulator",
                objective_function="reduce_consumer_harm_and_anticompetitive_behavior",
                risk_tolerance=0.19,
                cooperation_tendency=0.22,
                aggression_level=0.26,
                price_sensitivity=0.08,
                innovation_bias=0.21,
                capital_discipline=0.44,
                regulatory_sensitivity=0.97,
                time_horizon=10,
                memory_depth=16,
            ),
        },
        metadata={
            "initial_questions": [
                "Should the incumbent defend margin or accelerate AI investment?",
                "Can the AI-native startup grow before capital runs out?",
                "Does bundling reduce market openness?",
            ]
        },
    )
    return config, world
